### PR TITLE
Feature/double submit

### PR DESCRIPTION
**Pull request by grallewellyn**
Helping to prevent double submit by disabling submit button while job is submitting and displaying update of when last submitted under submit button
When missing field for form validation:
Screenshot 2023-11-02 at 11 51 29 AM
Job fails to submit:
Screenshot 2023-11-02 at 11 56 50 AM
Job successful:
Screenshot 2023-11-02 at 11 57 51 AM

### CODE REVIEW

**Comment by marjo-luc** [comment]
@grallewellyn Should we ask Rob to review the UX? I'm wondering whether or not we need both the toast and the content of the toast printed below the form. I'm also curious if the behavior of the form matches the corresponding maap-py behavior i.e. what does maap-py return if a user tries to submit a job without specifying a queue.

**Comment by grallewellyn** [comment]
@marjo-luc Rob was the one who suggested both the toast content and the content printed below the form: https://github.com/MAAP-Project/Community/issues/663. We discussed this in a maap hackathon and the logic was the user might miss the toast notification if they have multiple monitors 

What do you mean tries to submit a job without specifying a queue?
Screenshot 2023-11-10 at 11 46 57 AM
If they don't specify a resource it is a failed to submit error

**Comment by marjo-luc** [comment]
If a user tries to submit a job using maap-py within a notebook, and does not specify the queue/resource to use, what is the resulting behavior?

**Comment by grallewellyn** [comment]
Screenshot 2023-11-10 at 11 58 36 AM
This, but my UI changes shouldn't affect it

**Comment by marjo-luc** [comment]
The concern is not whether your changes will affect the UI or not -- it's ensuring consistent behavior and communication to users. In your maap-py example, it looks like the job is actually submitted, but if you provide the same inputs to the form and try to submit a job through there, you would get the messages indicating the job was not successfully submitted. Assuming the same inputs were provided, we should have the notebook maap-py and the UI request both submit the job or have them both fail to submit the job.

**Comment by grallewellyn** [comment]
Is that relevant for this PR though or should that be a different issue?
This PR doesn't change the result of submitting a job, just disables the submit button while the job is submitting and shows the toast content as text after the submit

**Comment by marjo-luc** [comment]
Ah, gotcha. Okay, if it's just the double submit stuff, then that's fine.

**Review by marjo-luc — APPROVED** [review]

**Comment by grallewellyn** [comment]
Thanks for approving and created an issue for the other problem!

**Comment by grallewellyn** [comment]
@marjo-luc Are you planning to publish a new version of dps soon, or should I publish a new version with this change?

**Pull request merged**
